services:
  postgres:
    image: postgres:13 # Use PostgreSQL version 13
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urlshortener
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data # Persistent storage

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  pgdata:
